// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    LlmArea: typeof import('./../src/components/llm/area.vue')['default']
    LlmDrawer: typeof import('./../src/components/llm/drawer.vue')['default']
    LlmFinetune: typeof import('./../src/components/llm/finetune.vue')['default']
    LlmHistoryButton: typeof import('./../src/components/llm/historyButton.vue')['default']
    LlmMain: typeof import('./../src/components/llm/main.vue')['default']
    LlmMessage: typeof import('./../src/components/llm/message.vue')['default']
    LlmMessageFrame: typeof import('./../src/components/llm/messageFrame.vue')['default']
    LlmSide: typeof import('./../src/components/llm/side.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    YButton: typeof import('./../src/components/y/button.vue')['default']
    YError: typeof import('./../src/components/y/error.vue')['default']
    YInput: typeof import('./../src/components/y/input.vue')['default']
    YLink: typeof import('./../src/components/y/link.vue')['default']
  }
}
